config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'items/create'
  get 'welcome/index'
  get 'welcome/about'
  get 'users/show'
  resources :items, only: [:create, :destroy]
  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
end

app/models/model.rb
class Model < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.user = current_user

    if @item.save
      flash[:notice] = "Item was saved."
      redirect_to(:users_show)
    else
      flash[:error] = "There was an error saving the item. Please try again."
    end
  end

  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
       flash[:notice] = "Item was deleted successfully."
       redirect_to(:users_show)
     else
       flash.now[:alert] = "There was an error deleting the item."
     end
  end
    private
  def item_params
    params.require(:item).permit(:name, :user)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
    @item = Item.new
    @items = @user.items
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/items/_form.html.erb
<h3> Add New To-Do Item </h3>

<%= form_for @item do |f| %>
  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', placeholder: "Enter new to-do item" %>
  </div>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/items/_item.html.erb
<% @user.items.each do |item| %>
  <div class="media">
    <div class="media-body">
      <h4 class="media-heading">
        <p><%= item.name %> <%= link_to "Delete", item, method: :delete, remote: true, class: 'glyphicon glyphicon-ok' %><%= distance_of_time_in_words(Time.now, item.created_at.to_date + 7 ) %>  left.</small>
</p>
      </h4>
    </div>
  </div>
<% end %>

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocitoff</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
     <ul style="text-align: right;" class="nav nav-tabs">
       <li><%= link_to "Home", welcome_index_path %> |
         <% if user_signed_in? %>
  You are signed in: <strong><%= current_user.email %></strong> |
   <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
<% else %>
  <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> |
  <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
<% end %>
       </li>
     </ul>
     <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
<%= yield %>
</div>
</body>
</html>

app/views/users/show.html.erb
<h2>Your To-Do List</h2>

<% if current_user %>
<div class="col-md-8">
        <%= render partial: 'items/item' %>
    </div>
    <div class="col-md-8">
        <%= render partial: 'items/form' %>
    </div>
<% end %>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1> Hellow world dldljd djfd kj </h1>